import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
import math
from typing import Callable, Generator
from numba import njit, complex128, int64, float64

def iterate(R: Callable[[complex], complex], z0: complex, max_iter: int):
    """
    Generates the orbit of z0 under the rational function R.
    Yields successive values until max_iter is reached or z escapes to infinity.
    """
    z = z0
    zn = [z0]
    
    for _ in range(max_iter):
        try:
            z = R(z)
            
            # Check for standard float infinity or NaN
            if math.isinf(z.real) or math.isnan(z.real):
                break
                
            zn.append(z)
            
        except (ZeroDivisionError, OverflowError):
            # Hit a pole exactly, or the float overflowed
            break
    
    return zn



def plot_sequence_dark(zn, center: complex, zoom):
    zn = np.array(zn)
    
    plt.figure(figsize=(10, 10))
    plt.style.use('dark_background')

    # 1. Use a brighter colormap like 'plasma', 'spring', or 'autumn'
    # 'plasma' is great because it goes from bright purple to yellow
    colors = np.linspace(0, 1, len(zn))
    
    # 2. Add a very thin line connecting the points so you can see the 'flow'
    plt.plot(zn.real, zn.imag, color='white', linewidth=0.5, alpha=0.3)

    # 3. Increase size (s) and remove transparency (alpha)
    plt.scatter(zn.real, zn.imag, c=colors, cmap='viridis', s=30, alpha=1.0, edgecolors='none')

    # Highlight start and end with distinct colors
    plt.scatter(zn.real[0], zn.imag[0], color='white', s=50, label='Start (z0)', zorder=5)
    plt.scatter(zn.real[-1], zn.imag[-1], color='red', s=50, label='End', zorder=5)

    plt.axhline(0, color='white', linewidth=0.5, alpha=0.3)
    plt.axvline(0, color='white', linewidth=0.5, alpha=0.3)
    
    # Labels and Grid
    plt.title(f"Möbius Iterations (Zoom: {zoom})")
    plt.legend(scatterpoints=1)
    plt.grid(alpha=0.1)

    # --- Zoom Settings ---
    plt.xlim(center.real - zoom, center.real + zoom)
    plt.ylim(center.imag - zoom, center.imag + zoom)
    plt.gca().set_aspect('equal', adjustable='box')
    
    plt.show()



# EXAMPLE FOR EFFICIENT ITERATION (generated by AI)

# Numba requires the function R to be JIT-compiled as well
@njit(complex128(complex128))
def R(z):
    return (z**2 + 1) / (z - 0.5)

@njit(int64(complex128, int64, float64))
def iterate_fast(z0, max_iter, escape_radius=1e10):
    # Pre-allocating an array is faster than appending if we know the max size
    # However, if you only need the *final* value or the *escape time*, 
    # you shouldn't store the array at all!
    
    z = z0
    for i in range(max_iter):
        # We must manually check denominator to avoid crashing the compiled C code
        if z == 0.5: 
            return i # Escaped at iteration i due to pole
            
        z = (z**2 + 1) / (z - 0.5)
        
        if abs(z) > escape_radius:
            return i # Returns the escape time
            
    return max_iter